- link:
  "~/AppData/Roaming/Code/User/snippets": editors/vscode/snippets
  "~/AppData/Roaming/Code/User/settings.json": editors/vscode/settings.json
  "~/AppData/Roaming/Code/User/keybindings.json": editors/vscode/keybindings.json

- shell:
  - [bash ./vscode/install.sh, Installing Visual Studion Code Extensions]